### ISSUE TITLE
Duplicate `/expenses` route

### ISSUE THREAD

**Issue by eemanioui** [auth0-training/labs-node-working-with-apis#10]
Hi Team,

At `Step #5 of 7 (2: Configure the Web Application to Pull Expenses from the API)` the instruction is to:

## Modify the Expenses Route
Now we'll modify the "/expenses" route in a similar way. Compare the block below to what's currently in the code. As before, we're adding error handling, and defining the path to the relevant data in our Expenses API.
```js
app.get("/expenses", requiresAuth(), async (req, res, next) => {
    try {
        const expenses = await axios.get(`${API_URL}/reports`);
        res.render("expenses", {
           user: req.oidc && req.oidc.user,
           expenses: expenses.data,
        });
    } catch (err) {
        next(err);
    }
});
```
↪ [Insert Code](https://fluffy-cod-6w9gj4q4gxxh5v6v.github.dev/) , then continue to the next step.

---
However, this ends up replacing the `user` endpoint handler instead as it is highlighted by default: 
![wrong highlighted section](https://github.com/auth0-training/labs-node-working-with-apis/assets/64502428/56b34997-ea92-4702-868f-111e464946c3)
> Please Note, I didn't highlight the `/user` endpoint handler in the above screenshot, it was highlight by default. 

After clicking on insert code, the `/user` endpoint handler is replaced by the new `/expenses` `Get` handler and we end up with 2 handlers for the same `GET` route, like so: 
![duplicate routes](https://github.com/auth0-training/labs-node-working-with-apis/assets/64502428/32f3f65e-5f3f-4244-b302-939e389b676e)

I even deleted the codespace lab and restarted it again and this time, I highlighted the `/expenses` endpoint to be replaced. However, the issue still persisted by replacing the `user` endpoint instead.
![doesn't work even when the right endpoint is highlighted](https://github.com/auth0-training/labs-node-working-with-apis/assets/64502428/f0c2456f-d0fc-4323-8646-9903e04a8db0)

**Comment by kazemicode** [comment]
Thanks for pointing this out! Code Tour accepts a param for line numbers and at some point the code must have been updated, throwing off the line numbers. We'll get this resolved shortly.
